name: commit

on:
  push:
    branches-ignore:
    - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: test
      run: |
        V=$(make version)
        VF="^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$"  # regexp to check correct version format
        if ! [[ "$V" =~ $VF ]]; then echo "Invalid version format"; exit 1; fi
        git tag "$V"
