name: merge

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        V=$(make version)
        git tag "$V"
        git push origin "$V"
  push:
    needs: tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: push
      run: |
        echo "helm package myapp"
        echo "help push myapp"
